server:
  port: 3001

spring:
  application:
    name: order-service-3001

eureka:
  instance:
    instance-id: order-service  #主机名称
    prefer-ip-address: true #微服务访问路径hover时显示ip地址
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/